#ifndef INC_2022_PROJECT_ORFEOTERKUCI_STANDARDVALUES_H
#define INC_2022_PROJECT_ORFEOTERKUCI_STANDARDVALUES_H

#define FRAMERATE               60
#define TICK_SPEED              (1.0/FRAMERATE)

#define MAX_VELOCITY            0.30
#define MAX_VERTICAL            8.00
#define ACCELERATION            5.00
#define AIR_ACCELERATION        1.00
#define GRAVITY_COEFFICIENT     9.81
#define DRAG_COEFFICIENT        0.095
#define AIR_RESISTANCE          0.015


#endif // INC_2022_PROJECT_ORFEOTERKUCI_STANDARDVALUES_H
